config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :friends
  get "home/about"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  def index
    @friends = Friend.all
  end

  def show
  end

  def new
    @friend = Friend.new
  end

  def edit
  end

  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friends_url(@friend), notice: "Friend was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friends_url(@friend), notice: "Friend was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
    end
  end

  private
    def set_friend
      @friend = Friend.find(params[:id])
    end

    def friend_params
      params.require(:friend).permit(:profile, :first_name, :last_name, :email, :phone, :instagram)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :instagram, style: "display: block" %>
    <%= form.text_field :instagram %>
  </div>

  <div>
    <%= form.label :profile, style: "display: block" %>
    <%= form.file_field :profile %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends List</h1>

<table class="table table-striped table-bordered table-hover" >
  <thead class="table-dark">
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Instagram</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @friends.each do |friend|%>
      <tr>
       <td><%= friend.first_name %></td>
       <td><%= friend.last_name %></td>
       <td><%= friend.email %></td>
       <td><%= friend.phone %></td>
       <td><%= friend.instagram %></td>
       <td>
        <%= link_to "Edit", edit_friend_path(friend), class:"btn btn-secondary" %>
        <%= link_to "Show", friend_path(friend), class:"btn btn-secondary" %>
        <%= link_to "Destroy", friend_path(friend), data: { "turbo-method": :delete }, class:"btn btn-secondary" %>
       </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friends/new.html.erb
<h1> Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<p id="notice"><%= notice %></p>

  <p>
    <strong>First name:</strong>
    <%= @friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @friend.phone %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= @friend.instagram %>
  </p>

</div>


<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary" %> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ,bg-body-tertiary btn-margin">
  <div class="container-fluid">
  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Friends', friends_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'New Friend', new_friend_path, class:"nav-link" %>
        </li>
      </ul>
      <li class=""nav-item>
        <div class="btn-margin">
          <% if current_user %>
            <%= button_to destroy_user_session_path,  method: :delete, class: "btn btn-danger" do %>
              <i class="fa-solid fa-right-from-bracket"></i>Logout
            <% end %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-secondary" %>
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-secondary" %>
          <% end %>
        </div>
      </li>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Welcome to my Friends app<h1>

app/views/home/index.html.erb
<h1>This is my index page</h1>
Hello World!

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends</title>
     <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
  <%= render 'home/header' %>
    <div class="container">
    <br>
     <%= yield %>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>